version: '3'
services:
  database:
    image: postgres:latest
    container_name: money-tracker-database
    ports:
      - ${DATABASE_PORT}:5432
    env_file:
      - .env.${NODE_ENV}
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - database_data:/data/db

  database-test:
    image: postgres:latest
    container_name: money-tracker-database-test
    ports:
      - ${DATABASE_PORT}:5432
    env_file:
      - .env.${NODE_ENV}
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - database_data_test:/data/db

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: pnpm exec dotenv -e .env.${NODE_ENV} -- nest start --watch
    container_name: money-tracker-app
    depends_on:
      - database
    ports:
      - ${PORT}:3000
    env_file:
      - .env.${NODE_ENV}
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME}?schema=public
    volumes:
      - .:/usr/src/app

volumes:
  database_data:
  database_data_test:
